products:
  - "抖音"
  - "douyin"
  - "dy"
  - "斗音"
  - "头条"
  - "toutiao"
  - "tiktok"
  - "西瓜视频"
  - "火山"
  - "飞书"
  - "懂车帝"
  - "番茄小说"
  - "字节"
  - "bytedance"
  - "巨量引擎"
  - "穿山甲"

actions:
  - "刷粉"
  - "刷赞"
  - "刷量"
  - "涨粉"
  - "播放量"
  - "上热门"
  - "账号"
  - "买号"
  - "卖号"
  - "养号"
  - "老号"
  - "白号"
  - "实名号"
  - "引流"
  - "跳转"
  - "私域"
  - "截流"
  - "站街"
  - "接单"
  - "代做"
  - "破解"
  - "过审"
  - "解封"
  - "数据"
  - "泄露"
  - "查档"
  - "社工"
  - "群发"
  - "协议"
  - "外挂"
  - "脚本"
  - "自动化"
